// Mock database data for development

import type { WorkerProfile, CompanyProfile, JobPosting } from "@/lib/types"

export const mockWorkers: WorkerProfile[] = [
  {
    id: 1,
    userId: 1,
    firstName: "Ramesh",
    lastName: "Kumar",
    profileImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=ramesh",
    bio: "Experienced electrician with 8 years of expertise",
    primaryTrade: "electrician",
    secondaryTrades: [],
    experienceLevel: "expert",
    yearsOfExperience: 8,
    skills: ["Wiring", "Panel Installation", "Troubleshooting"],
    certifications: ["Electrician License"],
    location: {
      city: "Mumbai",
      state: "Maharashtra",
      latitude: 19.076,
      longitude: 72.8777,
    },
    serviceRadius: 15,
    hourlyRate: 250,
    dailyRate: 1500,
    availability: {
      workingDays: ["mon", "tue", "wed", "thu", "fri", "sat"],
      hoursPerDay: 10,
      canWorkWeekends: true,
    },
    rating: 4.8,
    totalReviews: 45,
    totalJobsCompleted: 120,
    responseRate: 95,
    verified: true,
    backgroundCheckCompleted: true,
    createdAt: new Date("2023-01-15"),
    updatedAt: new Date("2025-11-06"),
  },
  {
    id: 2,
    userId: 2,
    firstName: "Priya",
    lastName: "Singh",
    profileImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=priya",
    bio: "Skilled plumber with modern techniques",
    primaryTrade: "plumber",
    secondaryTrades: ["general"],
    experienceLevel: "intermediate",
    yearsOfExperience: 5,
    skills: ["Pipe Installation", "Leak Repair", "Drainage"],
    location: {
      city: "Mumbai",
      state: "Maharashtra",
      latitude: 19.0876,
      longitude: 72.8654,
    },
    serviceRadius: 12,
    hourlyRate: 180,
    dailyRate: 1000,
    availability: {
      workingDays: ["mon", "tue", "wed", "thu", "fri"],
      hoursPerDay: 8,
      canWorkWeekends: false,
    },
    rating: 4.5,
    totalReviews: 28,
    totalJobsCompleted: 85,
    responseRate: 88,
    verified: true,
    backgroundCheckCompleted: true,
    createdAt: new Date("2023-06-20"),
    updatedAt: new Date("2025-11-06"),
  },
  {
    id: 3,
    userId: 3,
    firstName: "Vikram",
    lastName: "Patel",
    profileImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=vikram",
    bio: "General construction helper",
    primaryTrade: "general",
    secondaryTrades: ["mason"],
    experienceLevel: "entry",
    yearsOfExperience: 2,
    skills: ["Material Handling", "Basic Construction", "Site Cleaning"],
    location: {
      city: "Mumbai",
      state: "Maharashtra",
      latitude: 19.0566,
      longitude: 72.8194,
    },
    serviceRadius: 8,
    dailyRate: 600,
    availability: {
      workingDays: ["mon", "tue", "wed", "thu", "fri", "sat", "sun"],
      hoursPerDay: 12,
      canWorkWeekends: true,
    },
    rating: 4.2,
    totalReviews: 12,
    totalJobsCompleted: 35,
    responseRate: 92,
    verified: false,
    backgroundCheckCompleted: false,
    createdAt: new Date("2024-08-10"),
    updatedAt: new Date("2025-11-06"),
  },
]

export const mockEmployers: CompanyProfile[] = [
  {
    id: 1,
    userId: 4,
    companyName: "BuildCorp",
    logo: "https://api.dicebear.com/7.x/initials/svg?seed=BC",
    bio: "Professional construction and renovation services",
    website: "www.buildcorp.com",
    location: {
      city: "Mumbai",
      state: "Maharashtra",
      address: "123 Business Street, Mumbai",
      latitude: 19.0827,
      longitude: 72.8752,
    },
    contactPerson: {
      name: "Arjun Sharma",
      phone: "+91 9876543220",
      email: "contact@buildcorp.com",
    },
    industryTypes: ["Construction", "Renovation"],
    businessType: "medium",
    yearsInBusiness: 12,
    numberOfEmployees: 45,
    rating: 4.6,
    totalReviews: 120,
    totalJobsPosted: 340,
    jobsFilledSuccessfully: 325,
    averageResponseTime: 15,
    verified: true,
    backgroundCheckCompleted: true,
    paymentVerified: true,
    createdAt: new Date("2013-03-10"),
    updatedAt: new Date("2025-11-06"),
  },
  {
    id: 2,
    userId: 5,
    companyName: "Home Services Pro",
    logo: "https://api.dicebear.com/7.x/initials/svg?seed=HS",
    bio: "Quick and reliable home maintenance",
    location: {
      city: "Mumbai",
      state: "Maharashtra",
      address: "456 Service Avenue, Mumbai",
      latitude: 19.076,
      longitude: 72.8656,
    },
    contactPerson: {
      name: "Neha Desai",
      phone: "+91 9876543221",
      email: "info@homeservicespro.com",
    },
    industryTypes: ["Maintenance", "Repairs"],
    businessType: "small",
    yearsInBusiness: 5,
    rating: 4.4,
    totalReviews: 85,
    totalJobsPosted: 150,
    jobsFilledSuccessfully: 142,
    averageResponseTime: 20,
    verified: true,
    backgroundCheckCompleted: true,
    paymentVerified: true,
    createdAt: new Date("2020-05-15"),
    updatedAt: new Date("2025-11-06"),
  },
]

export const mockJobs: JobPosting[] = [
  {
    id: 1,
    employerId: 1,
    title: "Electrical Wiring Installation",
    description: "Need experienced electrician for residential wiring project",
    tradeCategory: "electrician",
    requiredSkills: ["Wiring", "Panel Installation"],
    jobDuration: "multi-day",
    startDate: new Date("2025-11-07"),
    endDate: new Date("2025-11-10"),
    estimatedDuration: 40,
    paymentType: "fixed",
    budget: { min: 15000, max: 20000, currency: "INR" },
    location: {
      city: "Mumbai",
      state: "Maharashtra",
      address: "123 Residential Complex, Mumbai",
      latitude: 19.076,
      longitude: 72.8777,
    },
    workersNeeded: 2,
    workersHired: 0,
    requiredExperience: "intermediate",
    status: "open",
    priority: "high",
    visibility: "public",
    applicants: [],
    createdAt: new Date("2025-11-06"),
    updatedAt: new Date("2025-11-06"),
  },
  {
    id: 2,
    employerId: 2,
    title: "Plumbing Repair and Installation",
    description: "Fix leaking pipes and install new bathroom fixtures",
    tradeCategory: "plumber",
    requiredSkills: ["Pipe Installation", "Leak Repair"],
    jobDuration: "single-day",
    startDate: new Date("2025-11-08"),
    paymentType: "hourly",
    budget: { min: 180, max: 250, currency: "INR" },
    location: {
      city: "Mumbai",
      state: "Maharashtra",
      address: "456 Apartment Complex, Mumbai",
      latitude: 19.0876,
      longitude: 72.8654,
    },
    workersNeeded: 1,
    workersHired: 0,
    requiredExperience: "entry",
    status: "open",
    priority: "medium",
    visibility: "public",
    applicants: [],
    createdAt: new Date("2025-11-06"),
    updatedAt: new Date("2025-11-06"),
  },
  {
    id: 3,
    employerId: 1,
    title: "General Construction Helper",
    description: "Assist with material handling and site preparation",
    tradeCategory: "general",
    requiredSkills: ["Material Handling"],
    jobDuration: "multi-day",
    startDate: new Date("2025-11-10"),
    endDate: new Date("2025-11-15"),
    estimatedDuration: 48,
    paymentType: "daily",
    budget: { min: 600, max: 700, currency: "INR" },
    location: {
      city: "Mumbai",
      state: "Maharashtra",
      address: "789 Construction Site, Mumbai",
      latitude: 19.0566,
      longitude: 72.8194,
    },
    workersNeeded: 3,
    workersHired: 0,
    requiredExperience: "any",
    status: "open",
    priority: "medium",
    visibility: "public",
    applicants: [],
    createdAt: new Date("2025-11-06"),
    updatedAt: new Date("2025-11-06"),
  },
]
